# Model
model_name_or_path: "./Qwen2.5-1.5B-Instruct"
model_type: "llm_decoder"
num_labels: 1
query_format: "query: {}"
document_format: "document: {}"
seq: "\n"
special_token: "</s>"


# Dataset
train_dataset: "../../../example_data/t2rank_100.jsonl"
# val_dataset: "../../../example_data/t2rank_100.small.jsonl" # some bug to fix
max_label: 1
min_label: 0
max_len: 1024
shuffle_rate: 0.0
train_group_size: 4 # Only valid for pairwise or listwise loss

# Training
output_dir: "./output/t2ranking_100_example_llm"

## Model Saving
save_on_epoch_end: 1
num_max_checkpoints: 5

## Hyperparameters
loss_type: "listwise_ce"  # "pointwise_bce" or "pointwise_mse" or "pairwise_hinge" or "listwise_ce"
epochs: 2
lr: 5e-5
batch_size: 3
seed: 666
warmup_proportion: 0.1
gradient_accumulation_steps: 2
mixed_precision: bf16 # "pairwise_hinge" only supports fp16

## Logging
log_interval: 10
log_with: "wandb" # "wandb" or "tensorboard"



